project:
  type: website
  output-dir: docs

website:
  title: "Lauren O'Brien"
  site-url: https://obrl-soil.github.io
  repo-url: https://github.com/obrl-soil/obrl-soil.github.io
  twitter-card:
    creator: "@obrl_soil"
  open-graph:
    locale: en_NZ
    image: images/obrlsoilavatarmon.jpg
  google-analytics:
    tracking-id: "G-TTL1M4BX0Y"
    storage: cookies
    anonymize-ip: true
  cookie-consent:
    type: implied
    style: simple
    palette: light
  navbar:
    background: light
    foreground: gray-600
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: blog.qmd
      - icon: rss
        href: blog.xml
    left:
      - icon: envelope-fill
        aria-label: Email
        href: mailto:obrlsoilau@gmail.com
      - text: "{{< fa brands bluesky >}}"
        aria-label: Bluesky
        href: https://bsky.app/profile/obrlsoil.bsky.social
        rel: me
      - icon: mastodon
        aria-label: Mastodon
        href: https://mastodon.social/@obrl_soil
        rel: me
      - icon: github
        aria-label: Github
        href: https://github.com/obrl-soil
        rel: me
  sidebar:
    style: docked
    border: false
    background: light
    foreground: gray-600
    alignment: left
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: blog.qmd
  page-footer:
    background: light
    foreground: gray-500
    border: false
    left: "© Copyright 2022 Lauren O'Brien. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    fontcolor: $gray-600

editor: visual

